DELIMITER $$
DROP EVENT IF EXISTS backups$$
CREATE EVENT backups
ON SCHEDULE EVERY 1 MONTH STARTS NOW()
DO
BEGIN	
	SELECT * FROM registroUT INTO OUTFILE 'copia_registroUT.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tAsignatura INTO OUTFILE 'copia_tAsignatura.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tCapacitacion INTO OUTFILE 'copia_tCapacitacion.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tCiclo INTO OUTFILE 'copia_tCiclo.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tCurso INTO OUTFILE 'copia_tCurso.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tObtiene INTO OUTFILE 'copia_tObtiene.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tPrepara INTO OUTFILE 'copia_tPrepara.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tSalidaProfesional INTO OUTFILE 'copia_tSalidaProfesional.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tTiene INTO OUTFILE 'copia_tTiene.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
    SELECT * FROM tUnidadTrabajo INTO OUTFILE 'copia_tUnidadTrabajo.txt' FIELDS TERMINATED BY ';' 
    OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n\r';
END;$$
